import { BrainCircuit, RefreshCw } from "lucide-react"
import { useEffect, useState, type FormEvent } from "react"
import { createMlRun, getMlRunEligibility, getMlRuns, reviewMlRun } from "../api"
import type { ReleaseEligibilityStatus, TrainingRunSummary } from "../types"
import { canSubmitReview, isValidManualRunInput } from "../uiGuards"

const stateStyle = (state: TrainingRunSummary["state"]) => state === "approved" ? "bg-emerald-100 text-emerald-800" : state === "failed" || state === "denied" ? "bg-rose-100 text-rose-800" : state === "awaiting_review" ? "bg-amber-100 text-amber-800" : "bg-slate-100 text-slate-700"
const shortDigest = (value: string | null) => value ? `${value.slice(0, 10)}…${value.slice(-8)}` : "Not available"

export function MlWorkflowPanel() {
  const [runs, setRuns] = useState<TrainingRunSummary[]>([])
  const [selected, setSelected] = useState<TrainingRunSummary | null>(null)
  const [eligibility, setEligibility] = useState<ReleaseEligibilityStatus | null>(null)
  const [triggerId, setTriggerId] = useState("")
  const [inputDigest, setInputDigest] = useState("")
  const [loading, setLoading] = useState(false)
  const [creating, setCreating] = useState(false)
  const [busy, setBusy] = useState(false)
  const [status, setStatus] = useState<string | null>(null)
  const load = async () => { setLoading(true); setStatus(null); try { setRuns((await getMlRuns()).runs) } catch { setStatus("Unable to load ML workflow runs. Refresh and try again.") } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const createRun = async (event: FormEvent) => { event.preventDefault(); if (!/^[A-Za-z0-9][A-Za-z0-9._-]{2,127}$/.test(triggerId) || !/^[a-f0-9]{64}$/.test(inputDigest)) { setStatus("Enter a valid trigger ID and 64-character lowercase SHA-256 digest."); return } setCreating(true); setStatus(null); try { const result = await createMlRun(triggerId, inputDigest); setStatus(result.run ? "Training run queued." : `No run created: ${result.trigger.reasonCode}.`); setTriggerId(""); setInputDigest(""); await load() } catch { setStatus("The training run request could not be submitted.") } finally { setCreating(false) } }
  const selectRun = async (run: TrainingRunSummary) => { setSelected(run); setEligibility(null); try { setEligibility((await getMlRunEligibility(run.runId)).eligibility) } catch { setStatus("Unable to load release eligibility status.") } }
  const decide = async (decision: "approve" | "deny") => { if (!canSubmitReview(selected) || !selected) return; setBusy(true); setStatus(null); try { await reviewMlRun(selected, decision); await load(); setSelected(null) } catch { setStatus("The review could not be recorded. Refresh the run and try again.") } finally { setBusy(false) } }
  return <section className="min-h-[calc(100vh-4rem)] bg-[#faf9f6] px-5 py-10 sm:px-8 sm:py-14 lg:px-12"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#777269]">Controlled intelligence</p><h1 className="mt-3 font-[Manrope] text-4xl font-semibold tracking-[-.035em] text-[#33312b]">ML workflow</h1><p className="mt-4 max-w-3xl text-[#65645e]">Review content-free training state and release readiness. Prompts, customer content, model secrets, and provider credentials never enter this console.</p></div><button type="button" onClick={() => void load()} disabled={loading} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#33312b] px-4 text-sm font-semibold text-white disabled:opacity-50"><RefreshCw className={loading ? "h-4 w-4 animate-spin" : "h-4 w-4"} />{loading ? "Refreshing…" : "Refresh runs"}</button></div>
    <form onSubmit={(event) => void createRun(event)} className="mt-6 grid gap-3 rounded-3xl border border-[#d6d0c6] bg-white p-5 sm:grid-cols-[1fr_1.5fr_auto] sm:items-end"><label className="text-xs font-semibold uppercase tracking-wide text-[#65645e]">Trigger ID<input value={triggerId} onChange={(event) => setTriggerId(event.target.value)} maxLength={128} className="mt-2 h-11 w-full rounded-xl border border-[#c9c2b8] px-3 font-mono text-sm" placeholder="manual-2026-08-20" /></label><label className="text-xs font-semibold uppercase tracking-wide text-[#65645e]">Input SHA-256 digest<input value={inputDigest} onChange={(event) => setInputDigest(event.target.value)} maxLength={64} className="mt-2 h-11 w-full rounded-xl border border-[#c9c2b8] px-3 font-mono text-sm" placeholder="64 lowercase hexadecimal characters" /></label><button type="submit" disabled={creating} className="h-11 rounded-xl bg-[#087f78] px-4 text-sm font-semibold text-white disabled:opacity-50">{creating ? "Queueing…" : "Queue run"}</button></form>
    {status ? <p role="alert" className="mt-5 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">{status}</p> : null}
    <div className="mt-8 overflow-hidden rounded-3xl border border-[#d6d0c6] bg-white shadow-sm"><div className="flex items-center gap-3 border-b border-[#ece8e0] px-5 py-4"><BrainCircuit className="h-5 w-5 text-[#087f78]" /><h2 className="font-[Manrope] text-lg font-semibold text-[#33312b]">Training runs</h2><span className="ml-auto text-xs text-[#817c73]">{runs.length} loaded</span></div>{runs.length === 0 && !loading ? <p className="px-5 py-12 text-center text-sm text-[#777269]">No training runs have been created.</p> : <div className="divide-y divide-[#ece8e0]">{runs.map((run) => <button type="button" key={run.runId} onClick={() => void selectRun(run)} className="grid w-full gap-4 px-5 py-5 text-left hover:bg-[#faf9f6] md:grid-cols-[1.2fr_.8fr_1fr] md:items-center"><div><p className="font-mono text-sm font-semibold text-[#33312b]">{run.runId}</p><p className="mt-1 text-xs text-[#817c73]">Profile {run.runProfileId} · record v{run.recordVersion}</p></div><div><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${stateStyle(run.state)}`}>{run.state.replace("_", " ")}</span>{run.failureCode ? <p className="mt-2 text-xs text-rose-700">Failure: {run.failureCode}</p> : null}</div><dl className="grid grid-cols-2 gap-x-5 gap-y-2 text-xs"><div><dt className="text-[#817c73]">Candidate digest</dt><dd className="mt-0.5 font-mono text-[#4a463f]">{shortDigest(run.candidateDigest)}</dd></div><div><dt className="text-[#817c73]">Evidence digest</dt><dd className="mt-0.5 font-mono text-[#4a463f]">{shortDigest(run.evidenceDigest)}</dd></div></dl></button>)}</div>}</div>
    {selected ? <aside className="mt-6 rounded-3xl border border-[#d6d0c6] bg-white p-6 shadow-sm" aria-label="Selected ML run"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-[#817c73]">Selected run</p><h2 className="mt-1 font-mono text-lg font-semibold text-[#33312b]">{selected.runId}</h2></div><button type="button" onClick={() => { setSelected(null); setEligibility(null) }} className="text-sm font-semibold text-[#65645e]">Close</button></div><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-[#817c73]">State</dt><dd className="mt-1 font-semibold text-[#33312b]">{selected.state.replace("_", " ")}</dd></div><div><dt className="text-[#817c73]">Record version</dt><dd className="mt-1 font-semibold text-[#33312b]">{selected.recordVersion}</dd></div><div><dt className="text-[#817c73]">Candidate digest</dt><dd className="mt-1 break-all font-mono text-xs text-[#4a463f]">{selected.candidateDigest ?? "Not available"}</dd></div><div><dt className="text-[#817c73]">Evidence digest</dt><dd className="mt-1 break-all font-mono text-xs text-[#4a463f]">{selected.evidenceDigest ?? "Not available"}</dd></div></dl>{eligibility ? <div className={`mt-5 rounded-2xl border p-4 ${eligibility.releaseEligible ? "border-emerald-200 bg-emerald-50" : "border-amber-200 bg-amber-50"}`}><p className="text-xs font-semibold uppercase tracking-wide text-[#65645e]">Release eligibility</p><p className="mt-1 font-semibold text-[#33312b]">{eligibility.status} · {eligibility.passedGateCount}/{eligibility.gateCount} gates passed</p><p className="mt-1 text-xs text-[#65645e]">Policy {eligibility.policyId} · evaluated {new Date(eligibility.evaluatedAt).toLocaleString()}</p></div> : <p className="mt-5 text-sm text-[#817c73]">No validated eligibility record is available.</p>}{selected.state === "awaiting_review" ? <div className="mt-6 flex flex-wrap gap-3 border-t border-[#ece8e0] pt-5"><button type="button" disabled={busy || !selected.candidateDigest || !selected.evidenceDigest} onClick={() => void decide("approve")} className="rounded-xl bg-emerald-700 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{busy ? "Saving…" : "Approve"}</button><button type="button" disabled={busy || !selected.candidateDigest || !selected.evidenceDigest} onClick={() => void decide("deny")} className="rounded-xl border border-rose-300 px-4 py-2.5 text-sm font-semibold text-rose-700 disabled:opacity-50">Deny</button><p className="basis-full text-xs text-[#817c73]">Approval remains blocked unless separately validated release-eligible evidence exists.</p></div> : null}</aside> : null}</div></section>
}
