import { apiRequest } from "../../lib/http"
import { array, isoDate, nullable, nonEmptyString, nonNegativeInteger, object, oneOf } from "../../lib/schema"
import type { ReleaseEligibilityStatus, TrainingRunState, TrainingRunSummary } from "./types"

const digest = (value: unknown) => { const result = nonEmptyString(value, 64); if (!/^[a-f0-9]{64}$/.test(result)) throw new Error("invalid digest"); return result }
export const parseRun = (value: unknown): TrainingRunSummary => {
  const input = object(value, ["runId", "triggerId", "inputDigest", "runProfileId", "state", "recordVersion", "createdAt", "startedAt", "finishedAt", "expiresAt", "runnerVersion", "evidenceDigest", "candidateDigest", "failureCode"])
  return {
    runId: nonEmptyString(input.runId, 128), triggerId: nonEmptyString(input.triggerId, 128), inputDigest: digest(input.inputDigest), runProfileId: nonEmptyString(input.runProfileId, 128),
    state: oneOf(input.state, ["queued", "validating", "training", "evaluating", "awaiting_review", "failed", "denied", "approved", "signing", "publishing", "staged", "canary", "stable"] as const),
    recordVersion: nonNegativeInteger(input.recordVersion), createdAt: isoDate(input.createdAt), startedAt: nullable(input.startedAt, isoDate), finishedAt: nullable(input.finishedAt, isoDate), expiresAt: isoDate(input.expiresAt), runnerVersion: nonEmptyString(input.runnerVersion, 128), evidenceDigest: nullable(input.evidenceDigest, digest), candidateDigest: nullable(input.candidateDigest, digest), failureCode: nullable(input.failureCode, nonEmptyString)
  }
}
export const getMlRuns = (limit = 50) => apiRequest<{ runs: TrainingRunSummary[] }>(`/admin/ml/runs?limit=${limit}`, {}, (value) => { const input = object(value, ["runs"]); return { runs: array(input.runs, parseRun, 100) } })
export const getMlRun = (runId: string) => apiRequest<{ run: TrainingRunSummary }>(`/admin/ml/runs/${encodeURIComponent(runId)}`, {}, (value) => { const input = object(value, ["run"]); return { run: parseRun(input.run) } })
export const reviewMlRun = (run: TrainingRunSummary, decision: "approve" | "deny", comment: string | null = null) => apiRequest<{ review: { status: "approved" | "denied" } }>(`/admin/ml/runs/${encodeURIComponent(run.runId)}/${decision}`, { method: "POST", body: JSON.stringify({ candidateDigest: run.candidateDigest, evidenceDigest: run.evidenceDigest, expectedRecordVersion: run.recordVersion, comment }) }, (value) => { const input = object(value, ["review"]); const review = object(input.review, ["status"]); return { review: { status: oneOf(review.status, ["approved", "denied"] as const) } } })
export const createMlRun = (triggerId: string, inputDigest: string) => apiRequest<{ trigger: { triggerId: string; status: "eligible" | "not-needed" | "rejected"; reasonCode: string }; run: TrainingRunSummary | null }>("/admin/ml/runs", { method: "POST", body: JSON.stringify({ triggerId, inputDigest, runProfileId: "profile-logistic-v1" }) }, (value) => { const input = object(value, ["trigger", "run"]); const trigger = object(input.trigger, ["triggerId", "status", "reasonCode"]); return { trigger: { triggerId: nonEmptyString(trigger.triggerId, 128), status: oneOf(trigger.status, ["eligible", "not-needed", "rejected"] as const), reasonCode: nonEmptyString(trigger.reasonCode, 128) }, run: input.run === null ? null : parseRun(input.run) } })
export const getMlRunEligibility = (runId: string) => apiRequest<{ eligibility: ReleaseEligibilityStatus | null }>(`/admin/ml/runs/${encodeURIComponent(runId)}/eligibility`, {}, (value) => { const input = object(value, ["eligibility"]); if (input.eligibility === null) return { eligibility: null }; const item = object(input.eligibility, ["status", "releaseEligible", "policyId", "candidateDigest", "evidenceDigest", "evaluatedAt", "passedGateCount", "gateCount"]); return { eligibility: { status: oneOf(item.status, ["release-eligible", "shadow-only"] as const), releaseEligible: item.releaseEligible === true, policyId: nonEmptyString(item.policyId, 128), candidateDigest: digest(item.candidateDigest), evidenceDigest: digest(item.evidenceDigest), evaluatedAt: isoDate(item.evaluatedAt), passedGateCount: nonNegativeInteger(item.passedGateCount), gateCount: nonNegativeInteger(item.gateCount) } } })
